default_language_version:
        python: python3.6

repos:
        - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v2.2.3
          hooks:
                  - id: flake8
        - repo: https://github.com/psf/black
          rev: 19.3b0
          hooks:
                  - id: black
        - repo: https://github.com/timothycrosley/isort
          rev: 4.3.21-2
          hooks:
                  - id: isort
                    entry: pipenv run isort -rc
